version: "3.9"

services:
    database:
        image: mysql:8.0.32-debian
        container_name: trackr-db
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: "trackr"
            MYSQL_DATABASE: "trackr"
            MYSQL_USER: "trackr"
            MYSQL_PASSWORD: "trackr"

volumes:
    dbdata:
        driver: local
