version: "3.9"

services:
    database:
        image: mysql:8.0.32-debian
        container_name: trackr-db
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "trackr"
            MYSQL_DATABASE: "trackr"
            MYSQL_USER: "trackr"
            MYSQL_PASSWORD: "trackr"
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 5s
            timeout: 10s
            retries: 10
        networks:
            trackr:
                ipv4_address: 172.18.0.4

    server:
        build: ./backend
        container_name: trackr-server
        ports:
            - "8080:8080"
        volumes:
            - .:/usr/app
        links:
            - database
        depends_on:
            database:
                condition: service_healthy
        restart: always
        networks:
            trackr:
                ipv4_address: 172.18.0.3
        extra_hosts:
            - "host.docker.internal:host-gateway"

    app:
        build: ./frontend
        container_name: trackr-frontend
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/app
        restart: always
        networks:
            trackr:
                ipv4_address: 172.18.0.2
        extra_hosts:
            - "host.docker.internal:host-gateway"

volumes:
    data:
        driver: local

networks:
    trackr:
        driver: bridge
        ipam:
            config:
                - subnet: 172.18.0.0/16
                  gateway: 172.18.0.1
