openapi: 3.0.0
info:
  title: trackr API
  description: 
    The trackr API enables you to write data to a field in a project of your
    choice. The API can be called just with any HTTP Client, like Postman,
    Insomnia, or even right here in the browser.
  version: 1.0.0
servers:
  - url: http://localhost:8080/api/
paths:
  /values:
    post:
      summary: Adds a value to a field in a project.
      description: Adds a value to a field in a project using the field's ID.
      requestBody:
        description: The request body containing the field's ID, the project's
                     API key, and the value you wish to add.
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AddValue'
      responses:
        200:
          description: An empty object indicating an successful operation.
          content:
            application/json:
              schema:  
                $ref: '#/components/schemas/Success'
        400:
          description: A client error.
          content:
            application/json:
              schema:  
                $ref: '#/components/schemas/Error'
        500:
          description: A server error.
          content:
            application/json:
              schema:  
                $ref: '#/components/schemas/Error'
components:
  schemas:
    AddValue:
      type: object
      properties:
        apiKey:
          type: string
          description: The project's API key used to authorize you.
        fieldId:
          type: number
          description: The ID of the field you wish to add a value to.
        value:
          type: number
          description: The value you wish to add.
      required:
        - apiKey
        - fieldId
        - value
        
    Error:
      type: object
      properties:
        error:
          type: string
          example: Invalid request parameters provided.
          description: The explanation of the error.
    Success:
      type: object
    